fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

ode_upload_profile_image:
    path:     /upload-profile-image
    defaults: { _controller: ODEUserBundle:Default:uploadProfilePicture }
    methods: [POST]