app:
    resource: @AppBundle/Controller/
    type:     annotation

homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

hellopage:
    path:     /hello/{name}
    defaults:  { _controller: AppBundle:Default:hello }