ode_user:
    resource: "@ODEUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }