services:
#    ode_analysis.example:
#        class: ODE\AnalysisBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

     my.twig.extension:
         class: ODE\AnalysisBundle\Extensions\Twig\ResultReadyExtension
         arguments:
               doctrine: "@doctrine"
         tags:
                - { name: twig.extension }